services:
  - type: web
    name: crop-care-frontend
    runtime: docker
    plan: free
    region: singapore
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    envVars:
      - key: BACKEND_URL
        fromService:
          type: web
          name: crop-care-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: FRONTEND_PUBLIC_URL
        fromService:
          type: web
          name: crop-care-frontend
          envVarKey: RENDER_EXTERNAL_URL

  - type: web
    name: crop-care-backend
    runtime: docker
    plan: free
    region: singapore
    rootDir: backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/actuator/health
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: local
      - key: JWT_SECRET
        generateValue: true
      - key: UPLOAD_DIR
        value: /app/uploads
      - key: APP_AI_PROVIDER
        value: mock
      - key: CORS_ORIGINS
        fromService:
          type: web
          name: crop-care-frontend
          envVarKey: RENDER_EXTERNAL_URL
