package com.cropportal.audit;

import com.cropportal.entity.AuditLog;
import com.cropportal.repository.AuditLogRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

@Service
@RequiredArgsConstructor
public class AuditExportService {
    private static final DateTimeFormatter DATE = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").withZone(ZoneId.systemDefault());
    private final AuditLogRepository auditLogRepository;

    public List<AuditLog> logs(Map<String, String> filters) {
        return auditLogRepository.findAll().stream()
                .filter(log -> contains(log.getUserName(), filters.get("user")))
                .filter(log -> contains(log.getRoleName(), filters.get("role")))
                .filter(log -> contains(log.getActivity(), filters.get("activity")))
                .filter(log -> contains(log.getStatus(), filters.get("status")))
                .filter(log -> contains(log.getAction(), filters.get("search")) || contains(log.getMetadata(), filters.get("search")) || contains(log.getUserName(), filters.get("search")))
                .sorted(Comparator.comparing(AuditLog::getCreatedAt, Comparator.nullsLast(Comparator.naturalOrder())).reversed())
                .toList();
    }

    public String csv(Map<String, String> filters) {
        StringBuilder csv = new StringBuilder("Timestamp,User Name,Role,Activity,Module,Action Performed,IP Address,Device,Browser,Operating System,Login Status,Status,Remarks\n");
        for (AuditLog log : logs(filters)) {
            csv.append(escape(format(log))).append(',')
                    .append(escape(log.getUserName())).append(',')
                    .append(escape(log.getRoleName())).append(',')
                    .append(escape(log.getActivity())).append(',')
                    .append(escape(log.getModule())).append(',')
                    .append(escape(log.getAction())).append(',')
                    .append(escape(log.getIpAddress())).append(',')
                    .append(escape(log.getDevice())).append(',')
                    .append(escape(log.getBrowser())).append(',')
                    .append(escape(log.getOperatingSystem())).append(',')
                    .append(escape(log.getLoginStatus())).append(',')
                    .append(escape(log.getStatus())).append(',')
                    .append(escape(log.getRemarks())).append('\n');
        }
        return csv.toString();
    }

    public byte[] excel(Map<String, String> filters) {
        String[] headers = {"Timestamp", "User Name", "Role", "Activity", "Module", "Action Performed", "IP Address", "Device", "Browser", "Operating System", "Login Status", "Status", "Remarks"};
        StringBuilder rows = new StringBuilder();
        rows.append("<row>");
        for (String header : headers) rows.append(cell(header));
        rows.append("</row>");
        for (AuditLog log : logs(filters)) {
            rows.append("<row>")
                    .append(cell(format(log))).append(cell(log.getUserName())).append(cell(log.getRoleName()))
                    .append(cell(log.getActivity())).append(cell(log.getModule())).append(cell(log.getAction()))
                    .append(cell(log.getIpAddress())).append(cell(log.getDevice())).append(cell(log.getBrowser()))
                    .append(cell(log.getOperatingSystem())).append(cell(log.getLoginStatus())).append(cell(log.getStatus()))
                    .append(cell(log.getRemarks())).append("</row>");
        }
        return xlsx(rows.toString());
    }

    public byte[] pdf(Map<String, String> filters) {
        StringBuilder text = new StringBuilder();
        text.append("AI Powered Crop Disease Detection and Farmer Support Portal\n");
        text.append("Audit Activity Report\nGenerated: ").append(DATE.format(java.time.Instant.now())).append("\n\n");
        for (AuditLog log : logs(filters)) {
            text.append(format(log)).append(" | ").append(value(log.getUserName())).append(" | ")
                    .append(value(log.getRoleName())).append(" | ").append(value(log.getActivity())).append(" | ")
                    .append(value(log.getStatus())).append(" | ").append(value(log.getRemarks())).append("\n");
        }
        text.append("\nGenerated by AI Powered Crop Disease Detection and Farmer Support Portal");
        return simplePdf(text.toString());
    }

    private boolean contains(String value, String filter) {
        return !StringUtils.hasText(filter) || value(value).toLowerCase().contains(filter.toLowerCase());
    }

    private String format(AuditLog log) {
        return log.getCreatedAt() == null ? "" : DATE.format(log.getCreatedAt());
    }

    private String escape(String value) {
        return '"' + value(value).replace("\"", "\"\"") + '"';
    }

    private String value(String value) {
        return value == null ? "" : value;
    }

    private String cell(String value) {
        return "<c t=\"inlineStr\"><is><t>" + xml(value(value)) + "</t></is></c>";
    }

    private byte[] xlsx(String rows) {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            try (ZipOutputStream zip = new ZipOutputStream(out)) {
                put(zip, "[Content_Types].xml", "<?xml version=\"1.0\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");
                put(zip, "_rels/.rels", "<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");
                put(zip, "xl/workbook.xml", "<?xml version=\"1.0\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Audit Logs\" sheetId=\"1\" r:id=\"rId1\"/></sheets></workbook>");
                put(zip, "xl/_rels/workbook.xml.rels", "<?xml version=\"1.0\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");
                put(zip, "xl/worksheets/sheet1.xml", "<?xml version=\"1.0\"?><worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\"><sheetData>" + rows + "</sheetData><autoFilter ref=\"A1:M1\"/></worksheet>");
            }
            return out.toByteArray();
        } catch (Exception ex) {
            return csv(Map.of()).getBytes(StandardCharsets.UTF_8);
        }
    }

    private void put(ZipOutputStream zip, String path, String content) throws Exception {
        zip.putNextEntry(new ZipEntry(path));
        zip.write(content.getBytes(StandardCharsets.UTF_8));
        zip.closeEntry();
    }

    private String xml(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }

    private byte[] simplePdf(String text) {
        String safe = text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)");
        String stream = "BT /F1 10 Tf 42 760 Td 14 TL (" + safe.replace("\n", ") Tj T* (") + ") Tj ET";
        String body = "1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj\n2 0 obj<</Type/Pages/Count 1/Kids[3 0 R]>>endobj\n3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>endobj\n4 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj\n5 0 obj<</Length " + stream.length() + ">>stream\n" + stream + "\nendstream endobj\n";
        return ("%PDF-1.4\n" + body + "trailer<</Root 1 0 R>>\n%%EOF").getBytes(StandardCharsets.UTF_8);
    }
}
